### ISSUE TITLE
Semantics of skip-till-any

### ISSUE THREAD

**Issue by ElAlev** [CORE-cer/CORE-paper#2]
Hi.

I have a question regarding the semantics of skip-till-any in CORE.

According to my understanding, under skip-till-any, the engine should detect all combinations of the events defined in the query that satisfy the "temporal" order constraints, regardless of whether any other events may occur in between.

For example, consider the query:
`SELECT ALL *
FROM S
WHERE (AA; AB; AC)
WITHIN 100 EVENTS
CONSUME BY ANY`

If we run CORE on the following stream:
`AH(id=0)
AC(id=1)
AB(id=2)
AH(id=3)
AD(id=4)
AF(id=5)
AG(id=6)
AC(id=7)
AB(id=8)
AH(id=9)
AC(id=10)
AB(id=11)
AG(id=12)
AG(id=13)
AB(id=14)
AB(id=15)
AC(id=16)
AC(id=17)
AE(id=18)
AC(id=19)
AI(id=20)
AD(id=21)
AE(id=22)
AA(id=23)
AF(id=24)
AB(id=25)
AD(id=26)
AB(id=27)
AD(id=28)
AB(id=29)
AB(id=30)
AB(id=31)
AE(id=32)
AI(id=33)
AB(id=34)
AH(id=35)
AI(id=36)
AD(id=37)
AI(id=38)
AA(id=39)
AH(id=40)
AA(id=41)
AA(id=42)
AA(id=43)
AH(id=44)
AF(id=45)
AF(id=46)
AF(id=47)
AB(id=48)
AH(id=49)
AD(id=50)
AF(id=51)
AA(id=52)
AA(id=53)
AA(id=54)
AC(id=55)
AE(id=56)
AA(id=57)
AE(id=58)
AA(id=59)
AA(id=60)
AF(id=61)
AD(id=62)
AH(id=63)
AH(id=64)
AI(id=65)
AA(id=66)
AH(id=67)
AH(id=68)
AH(id=69)
AD(id=70)
AA(id=71)
AA(id=72)
AG(id=73)
AF(id=74)
AA(id=75)
AC(id=76)
AC(id=77)
AA(id=78)
AD(id=79)
AG(id=80)
AG(id=81)
AH(id=82)
AF(id=83)
AH(id=84)
AH(id=85)
AA(id=86)
AH(id=87)
AG(id=88)
AH(id=89)
AB(id=90)
AE(id=91)
AC(id=92)
AC(id=93)
AF(id=94)
AG(id=95)
AF(id=96)
AH(id=97)
AI(id=98)
AB(id=99)
AF(id=100)`

Then we get the following matches from CORE:
AA(id=43.0) AB(id=48.0) AC(id=55.0) 
AA(id=42.0) AB(id=48.0) AC(id=55.0) 
AA(id=41.0) AB(id=48.0) AC(id=55.0) 
AA(id=39.0) AB(id=48.0) AC(id=55.0) 
AA(id=23.0) AB(id=48.0) AC(id=55.0) 
AA(id=23.0) AB(id=34.0) AC(id=55.0) 
AA(id=23.0) AB(id=31.0) AC(id=55.0) 
AA(id=23.0) AB(id=30.0) AC(id=55.0) 
AA(id=23.0) AB(id=29.0) AC(id=55.0) 
AA(id=23.0) AB(id=27.0) AC(id=55.0) 
AA(id=86.0) AB(id=90.0) AC(id=92.0) 
AA(id=78.0) AB(id=90.0) AC(id=92.0) 
AA(id=75.0) AB(id=90.0) AC(id=92.0) 
AA(id=72.0) AB(id=90.0) AC(id=92.0) 
AA(id=71.0) AB(id=90.0) AC(id=92.0) 
AA(id=66.0) AB(id=90.0) AC(id=92.0) 
AA(id=60.0) AB(id=90.0) AC(id=92.0) 
AA(id=59.0) AB(id=90.0) AC(id=92.0) 
AA(id=57.0) AB(id=90.0) AC(id=92.0)

However, if the semantics are as described above (i.e., all combinations of AA; AB; AC in that order, regardless of other events between AA and AB or AB and AC), then it seems that some matches are missing. For example, AA(id=23.0) AB(id=25.0) AC(id=92.0)  should be a match. In fact, it seems that there are 70 matches missing from the results produced by CORE. 

So, the question is the following: 
Is my understanding of skip-till-any in CORE correct? If yes, then why aren't all matches being produced? If no, could you please explain what the semantics of skip-till-any in CORE is?

Thanks.

**Comment by svsummer** [comment]
In CORE you should use CONSUME BY NONE to produce  all complex events that satisfy the temporal ordering constraints.

CONSUME BY ANY has a different semantics: as soon as it finds the match it erases the history of events seen so far, and starts matching the pattern again from the next event onwards.
